const data: Record<TProductId, TProduct> = {
	'2zd33b8c': {
		name: 'GeForce GTX 1050Ti',
		id: '2zd33b8c',
		sku: 'NUR72KCM',
		price: 150,
		image: '/images/1050.jpg',
		attributes: {
			description: 'Videocard 4GB GDDR5 OC Dual Fan',
			manufacturer: 'MSI',
			vram: '4 GB',
			stars: '⭐',
		},
	},
	'6trfgkkj': {
		name: 'ASUS GeForce GTX 1650',
		id: '6trfgkkj',
		sku: 'AX4M8SJV',
		price: 300,
		image: '/images/1650.jpg',
		attributes: {
			description: 'Videocard 4GB GDDR6 TUF GAMING OC',
			manufacturer: 'ASUS',
			vram: '4 GB',
			stars: 'Base: ⭐⭐ Super: ⭐⭐⭐',
		},
	},
	'7bcr49em': {
		name: 'GeForce RTX 2060',
		id: '7bcr49em',
		sku: 'HYA78F6J',
		price: 450,
		image: '/images/2060.jpg',
		attributes: {
			description: 'Videocard 6GB DDR6 w/ Ray Tracing',
			manufacturer: 'ZOTAC',
			vram: '6 GB',
			stars: '⭐⭐⭐⭐',
		},
	},
	'098323ks': {
		name: 'GeForce RTX 3080',
		id: '098323ks',
		sku: 'BXD100BLK',
		price: 1600,
		image: '/images/3080.jpg',
		attributes: {
			description: 'Videocard 24GB GDDR6 w/ LEDS',
			manufacturer: 'EVGA',
			vram: '24 GB',
			stars: '⭐⭐⭐⭐⭐',
		},
	},
	b8uthe2y: {
		name: 'GeForce RTX 3090',
		id: 'b8uthe2y',
		sku: 'RMRCZN7E',
		price: 600,
		image: '/images/3060.jpg',
		attributes: {
			description: 'Videocard 24GB GDDR6 w/ 3 coolers',
			manufacturer: 'ASUS',
			vram: '24 gb',
			stars: '⭐⭐⭐⭐',
		},
	},
	ewxsd6xb: {
		name: 'GeForce RTX 3090',
		id: 'ewxsd6xb',
		sku: 'N55229ZA',
		price: 1999,
		image: '/images/3090.jpg',
		attributes: {
			description: 'Videocard 24GB GDDR6 4.0',
			manufacturer: 'ROG STRIX',
			vram: '24 GB',
			stars: '⭐⭐⭐⭐⭐',
		},
	},
	fpr72m9k: {
		name: 'NVIDIA Tesla V100',
		id: 'fpr72m9k',
		sku: 'B4HZ42TM',
		price: 9450,
		image: '/images/tesla.jpg',
		attributes: {
			description: 'Videocard 900 GB/s 1465 Mhz 7.5 TFLOPS in FP64 ',
			manufacturer: 'Ellongated Musket',
			vram: '900 GB',
			stars: 'For Gaming: ⭐ For AI/Data Science: ⭐⭐⭐⭐⭐',
		},
	},
	t9dv25gs: {
		name: 'Ultra Gaming Toaster Super 32GB',
		id: 't9dv25gs',
		sku: 'ZY3T9XXC',
		price: 12945,
		image: '/images/toaster.jpg',
		attributes: {
			description: 'The most performanceful (??) Videocard in the entire World',
			manufacturer: 'The best manufacturer in the world',
			vram: '∞',
			stars: '⭐⭐⭐⭐⭐⭐⭐ - ♾♾',
		},
	},
	t345w48y: {
		name: 'What even is this?',
		id: 't345w48y',
		sku: 'MW79ZZ6Y',
		price: 2,
		image: '/images/what.jpg',
		attributes: {
			description: 'What the hell?',
			manufacturer: 'Who can even build this shit?',
			vram: 'Does it even has?',
			stars: '???',
		},
	},
};

export default data;
